-- Responsabilidad (V2): seed categorías. Tablas = Hibernate antes de Flyway.
-- Ver backend/docs/AGENDA_FLYWAY_MIGRATIONS.md
-- icono: claves consumidas por AgendaIconRegistry (Flutter) y API pública.

INSERT INTO agenda_categories (id, nombre, slug, icono, synonyms, activo, created_at, updated_at) VALUES
    (gen_random_uuid(), 'Peluquería',  'peluqueria',  'scissors',
        '["peluqueria","peluquero","peluquera","pelu","corte de pelo","cabello","salón de belleza","salon","peinado"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Barbería',    'barberia',    'razor',
        '["barberia","barbero","barba","afeitado","corte masculino","fade"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Manicure',    'manicure',    'hand',
        '["manicure","manicura","uñas","uñitas","mani","esmalte","nail","nails","gel"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Pedicure',    'pedicure',    'foot',
        '["pedicure","pedicura","pies","uñas de los pies","pedi"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Spa',         'spa',         'sparkles',
        '["spa","relax","relajacion","relajación","jacuzzi","sauna","wellness","aromaterapia"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Yoga',        'yoga',        'lotus',
        '["yoga","yogui","meditación","meditacion","mindfulness"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Gimnasio',    'gimnasio',    'dumbbell',
        '["gimnasio","gym","fitness","entrenamiento","pesas","funcional"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'CrossFit',    'crossfit',    'crossfit',
        '["crossfit","cross fit","wod","funcional intenso"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Entrenamiento personal', 'entrenamiento', 'personal_training',
        '["entrenamiento personal","personal trainer","coach","pt"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Pilates',     'pilates',     'pilates',
        '["pilates","reformer","mat pilates"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Tatuajes',    'tatuajes',    'needle',
        '["tatuajes","tatuaje","tattoo","tatuador","piercing","microblading"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Masajes',     'masajes',     'hands',
        '["masajes","masaje","masajista","masoterapia","terapéutico","descontracturante"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Estética',    'estetica',    'mirror',
        '["estetica","estética","belleza","tratamiento facial","lifting"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Depilación',  'depilacion',  'wax',
        '["depilacion","depilación","cera","laser","ipl"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Maquillaje',  'maquillaje',  'makeup',
        '["maquillaje","makeup","make up","novia","social"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Cejas y pestañas', 'cejas', 'eyebrows',
        '["cejas","pestañas","lifting","laminado","extensiones"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Salud',       'salud',       'stethoscope',
        '["salud","consultorio","medicina","medico","médico","clinica","clínica","turno medico"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Odontología', 'odontologia', 'healing',
        '["odontologia","odontología","dental","dentista","ortodoncia","blanqueamiento"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Psicología',  'psicologia',  'psychology',
        '["psicologia","psicología","terapia","psicoterapia","salud mental","counseling"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Nutrición',   'nutricion',   'nutrition',
        '["nutricion","nutrición","dieta","alimentacion","alimentación","nutricionista"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Fisioterapia','fisioterapia','physiotherapy',
        '["fisioterapia","kinesiologia","kinesiología","rehabilitacion","rehabilitación"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Quiropráctica','quiropractica','chiropractic',
        '["quiropractica","quiropráctica","columna","quiropraxia"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Acupuntura',  'acupuntura',  'acupuncture',
        '["acupuntura","medicina china","agujas"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Podología',   'podologia',   'foot',
        '["podologia","podología","pie","pies","uñero"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Veterinaria', 'veterinaria', 'paw',
        '["veterinaria","veterinario","mascota","perro","gato","pet"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Clases y talleres', 'clases', 'school',
        '["clases","talleres","curso","cursos","capacitacion","capacitación","workshop"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Idiomas',     'idiomas',     'language',
        '["idiomas","ingles","inglés","portugues","portugués","frances","francés"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Música',      'musica',      'music',
        '["musica","música","canto","instrumento","clases de musica"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Fotografía',  'fotografia',  'camera',
        '["fotografia","fotografía","sesion","sesión","retrato","estudio"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Eventos',     'eventos',     'event',
        '["eventos","fiesta","salon","salón","cumpleaños","casamiento"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Gastronomía', 'gastronomia', 'restaurant',
        '["gastronomia","gastronomía","restaurante","mesa","reserva mesa","cena"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Coworking',   'coworking',   'coworking',
        '["coworking","oficina","sala","espacio de trabajo"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Limpieza',    'limpieza',    'cleaning',
        '["limpieza","higiene","sanitizacion","sanitización","domestica"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Taller mecánico', 'mecanica', 'wrench',
        '["mecanica","mecánica","auto","vehiculo","vehículo","service","taller"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Legal',       'legal',       'gavel',
        '["legal","abogado","abogada","notarial","escribano"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Contabilidad','contabilidad','calculator',
        '["contabilidad","contador","impuestos","finanzas","monotributo"]'::jsonb, true, now(), now()),
    (gen_random_uuid(), 'Inmobiliaria','inmobiliaria','home',
        '["inmobiliaria","propiedad","alquiler","visita","tasacion","tasación"]'::jsonb, true, now(), now())
ON CONFLICT (slug) DO NOTHING;
